kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: ML/Dockerfile
    repo: drone/docker
    username: hub_username
    password:
      $secret: hub_pwd