kind: pipeline
type: docker
name: default

steps:
- name: publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: ML/Dockerfile
    registry: registry.hub.docker.com
    repo: registry.hub.docker.com/ianjuan/parkinsonsdrawingsanalysis
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password