kind: pipeline
type: docker
name: default

steps:
- name: publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: ML/Dockerfile
    repo: ianjuan/parkinsonsdrawingsanalysis
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
  commands:
    - kubectl create -f job_foo.yaml
    - kubectl wait --for=condition=complete -f job_foo.yaml