kind: pipeline
type: docker
name: test

steps:
  # 事件一
  - name: cat file                           # 事件一：可自行定義的名稱
    image: alpine                        # 使用 alpine 容器
    commands:                            # 預執行的 shell 指令，這邊印出 hosts 內容
      - cat Test.txt
    when: echo "test"