kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: arm64

steps:
  - name: cat file                          
    image: alpine                       
    commands:                        
      - cat Test.txt
      - pwd
      - ls